### ISSUE TITLE
Twitter Age Restricted Videos 

### ISSUE THREAD

**Issue by PortalRex** [0x464e/tiktok_to_discord#5]
Twitter broke yt-dlp bypassing age restricted videos without having auth. https://github.com/yt-dlp/yt-dlp/issues/6763

**Comment by 0x464e** [comment]
I'm using [gallery-dl](https://github.com/mikf/gallery-dl) for Twitter, but yes, naturally gallery-dl seems to be affected as well.  
Right now I don't have time to see what could be done about it.

**Comment by PortalRex** [comment]
~~Twitter now requires an account to view posts. Elon just trying to shaft us.~~ Seems like it was reversed.
