### ISSUE TITLE
File Placement

### ISSUE THREAD

**Issue by iseeface** [0x464e/tiktok_to_discord#6]
Is my file placement correct for yt-dlp?, because I have the issue "Error: connect ECONNREFUSED ::1:80"

![image](https://github.com/0x464e/tiktok_to_discord/assets/67980665/19a7bf1a-f4d7-48cd-b71c-94d8a25db462)
![image](https://github.com/0x464e/tiktok_to_discord/assets/67980665/971452b1-ac75-4d75-85d7-3489b25f5cdf)

**Comment by 0x464e** [comment]
Hmm, if the path was wrong, the error should be `Error: spawn <path you have configured> ENOENT`.  
You should have `./yt-dlp` or `./yt-dlp.exe` in your config.json, yes? 

Or if you still have just `yt-dlp` in the config, it's also trying to use a global yt-dlp installation. Any chance you still have that in your config and have some outdated yt-dlp installed globally?

And is that error embed the only code you've modified, or have you changed some other code as well which could cause this?

Also, as a side note, expect a complete rewrite of this program in the near future. Now that I've also created [slideshow-video](https://github.com/0x464e/slideshow-video), I can also handle slideshow TikToks and create videos of them.
